### ISSUE TITLE
2.78 support?

### ISSUE THREAD

**Issue by dilom** [Dancovich/libgdx_blender_g3d_exporter#12]
I seem to have a problem to enable the plugin with blender 2.78. Is that version supported?

**Comment by Dancovich** [comment]
I'm using Blender 2.78 and it is working fine. Do you have an error log you can send me?

Also are you using the latest release (0.2.6)? The previous release had a problem when using Python 3.5.2 and up so if you where using 0.2.5 or below that might be it.

**Comment by dilom** [comment]
How can I tell which release I am using? I just updated to 2.78b-2 from 2.78b-1. The plugin is listed under "Missing script files" in the addon manager with an icon indicating something is wrong.

**Comment by dilom** [comment]
Ok, it works now! I didn't import it correctly into blender. I just installed the zip file from master and apparently blender didn't like that very much. I think it worked that way before but apparently it just wants the io_scene_g3d directory in the addons.

**Comment by Dancovich** [comment]
Nice. Don't know how it worked before, according to the wiki (https://github.com/Dancovich/libgdx_blender_g3d_exporter/wiki/Installation) you do need to copy the io_scene_g3d folder inside the addons directory.

Anyway, nice that you where able to fix it.
