### ISSUE TITLE
Export issues

### ISSUE THREAD

**Issue by wdavies973** [Dancovich/libgdx_blender_g3d_exporter#18]
Hello,

I'm attempting to use the Blender G3D plugin to export a animated, textured model using Cycles.

When I click "export", I get the following error message:
https://imgur.com/a/If57S0M

Here's my .blend file:
https://files.fm/u/6xu2tfgq

Let me know if you need any more information.

**Comment by Dancovich** [comment]
The cycles engine isn't supported by the exporter (or libGDX) but it should at least fail gracefully.  Thanks for the report.

**Comment by wdavies973** [comment]
Oh okay, good to know. Thanks!

**Comment by xahon** [comment]
I tried to export with default blender renderer and have the same issue

**Comment by xahon** [comment]
No, sorry. It's slightly different. This occurs only if I export to `.g3dj` format 
![image](https://user-images.githubusercontent.com/18731681/43077883-18967f14-8ecc-11e8-9e70-b0b47cf82508.png)
