### ISSUE TITLE
Needs an update to blender 2.74

### ISSUE THREAD

**Issue by Kerai** [Dancovich/libgdx_blender_g3d_exporter#4]
See for yourself.

**Comment by Dancovich** [comment]
I'll take a look, thanks for the report.

**Comment by plasmasolutions** [comment]
@Kerai what is not working in 2.74? Rule #1 in open source projects: No fixes without good reports!

**Comment by Dancovich** [comment]
Version 0.2.0 is compatible with Blender 2.76, latest version at this moment.

**Comment by Kerai** [comment]
uhuh this is very nice
